baseURL: /
languageCode: en-us
title: 94xychen
theme: ezhil

# themes configurations
copyright: © Copyright 94xychen
pygmentsstyle: solarized-dark
pygmentscodefences: true
pygmentscodefencesguesssyntax: true
googleAnalytics: "UA-158590129-1"
disqusShortname: ""
paginate: 10
params:
  subtitle: >-
    Digging Deeper
  mainSections:
    - posts
  disableDisqusTypes:
    - page
  featherIconsCDN: true
  favicon: icons/favicon.png
  mode: dark
  # customCSS: css/custom.css
  # customDarkCSS: css/custom-dark.css
  # customJS:
    # - 'https://code.jquery.com/jquery-3.4.1.js'
  social:
    - name: ChenXiyu
      icon: github
      url: 'https://github.com/ChenXiyu'
    # - name: Twitter
    #   icon: twitter
    #   url: 'https://twitter.com/gohugoio'
menu:
  main:
    - name: Home
      url: /
      weight: 100
    - name: All posts
      url: /posts
      weight: 200
    # - name: About
    #   url: /about
    #   weight: 3
    - name: Tags
      url: /tags
      weight: 400
    - name: Categories
      url: /categories
      weight: 500
taxonomies:
  tag: tags
  category: categories
