baseURL: /
title: 94xychen's Blog
theme: hugo-notepadium
copyright: ©2019 94xychen.
googleAnalytics: "UA-158590129-1"
disqusShortname: "chenxiyu"
hasCJKLanguage: true
enableRobotsTXT: true
markup:
  highlight:
    codeFences: true
    noClasses: false
  goldmark:
    renderer:
      unsafe: true
params:
  style: auto
  dateFormat: 'Monday, January 2, 2006'
  logo: images/logo.png
  slogan: Digging Deeper
  license: ''
  comments:
    enable: true
  math:
    enable: enable
    use: katex
  syntax:
    use: none
    theme: xcode
    darkTheme: xcode-dark
  nav:
    showCategories: false
    showTags: false
    custom:
      - title: Github
        url: https://github.com/chenxiyu
      # - title: Hugo
      #   url: 'https://gohugo.io/'
